INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (004, 0093, "AF", "AFG", "Afeganistão", "República Islâmica do Afeganistão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (008, 0355, "AL", "ALB", "Albânia", "República da Albânia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (012, 0213, "DZ", "DZA", "Algéria", "República Democrática Popular da Algéria")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (016, 1684, "AS", "ASM", "Samoa Americana", "Território de Samoa Americana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (020, 0376, "AD", "AND", "Andorra", "Principado Andorra")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (024, 0244, "AO", "AGO", "Angola", "República de Angola")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (660, 1264, "AI", "AIA", "Anguilla", "Anguilla")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (010, 0672, "AQ", "ATA", "Antártida", "Antártida")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (028, 1268, "AG", "ATG", "Antigua e Barbuda", "Antigua e Barbuda")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (032, 0054, "AR", "ARG", "Argentina", "República Argentina")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (051, 0374, "AM", "ARM", "Armênia", "República da Armênia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (533, 0297, "AW", "ABW", "Aruba", "Aruba")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (036, 0061, "AU", "AUS", "Austrália", "Comunidade da Austrália")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (040, 0043, "AT", "AUT", "Áustria", "República da Áustria")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (031, 0994, "AZ", "AZE", "Azerbaijão", "República do Azerbaijão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (044, 1242, "BS", "BHS", "Bahamas", "Comunidade de Bahamas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (048, 0973, "BH", "BHR", "Bahrein", "Reino do Bahrein")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (050, 0880, "BD", "BGD", "Bangladesh", "República Popular de Bangladesh")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (052, 0246, "BB", "BRB", "Barbados", "Barbados")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (112, 0375, "BY", "BLR", "Bielorrússia", "República da Bielorrússia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (056, 0032, "BE", "BEL", "Bélgica", "Reino da Bélgica")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (084, 0501, "BZ", "BLZ", "Belize", "Belize")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (204, 0229, "BJ", "BEN", "Benin", "República do Benin")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (060, 1441, "BM", "BMU", "Bermuda", "Bermuda")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (064, 0975, "BT", "BTN", "Butão", "Reino do Butão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (068, 0591, "BO", "BOL", "Bolívia", "Estado Plurinacional da Bolívia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (070, 0387, "BA", "BIH", "Bósnia e Herzegovina", "Bósnia e Herzegovina")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (072, 0267, "BW", "BWA", "Botswana", "República da Botswana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (074, 0047, "BV", "BVT", "Ilha Bouvet", "Ilha Bouvet")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (076, 0055, "BR", "BRA", "Brasil", "República Federativa do Brasil")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (086, 0246, "IO", "IOT", "Território Britânico do Oceano Índico", "Território Britânico do Oceano Índico")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (096, 0673, "BN", "BRN", "Brunei", "Estado do Brunei Darussalam")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (100, 0359, "BG", "BGR", "Bulgária", "República da Bulgária")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (854, 0226, "BF", "BFA", "Burkina Faso", "Burkina Faso")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (108, 0257, "BI", "BDI", "Burundi", "República do Burundi")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (116, 0855, "KH", "KHM", "Camboja", "Reino do Camboja")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (120, 0237, "CM", "CMR", "Camarões", "República de Camarões")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (124, 0001, "CA", "CAN", "Canadá", "Canadá")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (132, 0238, "CV", "CPV", "Cabo Verde", "República do Cabo Verde")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (136, 1345, "KY", "CYM", "Ilhas Cayman", "Ilhas Cayman")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (140, 0236, "CF", "CAF", "República Centro-Africana", "República Centro-Africana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (148, 0235, "TD", "TCD", "Chade", "República do Chade")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (152, 0056, "CL", "CHL", "Chile", "República do Chile")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (156, 0086, "CN", "CHN", "China", "República Popular da China")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (162, 0061, "CX", "CXR", "Ilha Christmas", "Território da Ilha Christmas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (166, 0672, "CC", "CCK", "Ilhas Cocos (Keeling)", "Território das Ilhas Cocos (Keeling)")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (170, 0057, "CO", "COL", "Colômbia", "República da Colômbia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (174, 0269, "KM", "COM", "Comores", "União das Comores")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (178, 0242, "CG", "COG", "Congo", "República do Congo")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (180, 0242, "CD", "COD", "Congo (DR)", "República Democrática do Congo")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (184, 0682, "CK", "COK", "Ilhas Cook", "Ilhas Cook")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (188, 0506, "CR", "CRI", "Costa Rica", "República da Costa Rica")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (384, 0225, "CI", "CIV", "Costa do Marfim", "República da Costa do Marfim")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (191, 0385, "HR", "HRV", "Croácia", "República da Croácia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (192, 0053, "CU", "CUB", "Cuba", "República de Cuba")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (196, 0357, "CY", "CYP", "Chipre", "República do Chipre")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (203, 0420, "CZ", "CZE", "República Tcheca", "República Tcheca")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (208, 0045, "DK", "DNK", "Dinamarca", "Reino da Dinamarca")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (262, 0253, "DJ", "DJI", "Djibuti", "República do Djibuti")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (212, 1767, "DM", "DMA", "Dominica", "Comunidade da Dominica")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (214, 1809, "DO", "DOM", "República Dominicana", "República Dominicana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (218, 0593, "EC", "ECU", "Equador", "República do Equador")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (818, 0020, "EG", "EGY", "Egito", "República Árabe do Egito")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (222, 0503, "SV", "SLV", "El Salvador", "República El Salvador")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (226, 0240, "GQ", "GNQ", "Guiné Equatorial", "República do Guiné Equatorial")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (232, 0291, "ER", "ERI", "Eritreia", "Estado da Eritreia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (233, 0372, "EE", "EST", "Estônia", "República da Estônia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (231, 0251, "ET", "ETH", "Etiópia", "República Democrática Federal da Etiópia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (238, 0500, "FK", "FLK", "Ilhas Malvinas", "Ilhas Malvinas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (234, 0298, "FO", "FRO", "Ilhas Faroe", "Ilhas Faroe")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (242, 0679, "FJ", "FJI", "Fiji", "República do Fiji")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (246, 0358, "FI", "FIN", "Finlândia", "República da Finlândia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (250, 0033, "FR", "FRA", "França", "República Francesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (254, 0594, "GF", "GUF", "Guiana Francesa", "Guiana Francesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (258, 0689, "PF", "PYF", "Polinésia Francesa", "Polinésia Francesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (260, 0033, "TF", "ATF", "Terras Austrais e Antárticas Francesas", "Território das Terras Austrais e Antárticas Francesas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (266, 0241, "GA", "GAB", "Gabão", "República Gabonesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (270, 0220, "GM", "GMB", "Gâmbia", "República da Gâmbia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (268, 0995, "GE", "GEO", "Geórgia", "Geórgia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (276, 0049, "DE", "DEU", "Alemanha", "República Federal da Alemanha")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (288, 0233, "GH", "GHA", "Gana", "Repúblia de Gana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (292, 0350, "GI", "GIB", "Gibraltar", "Gibraltar")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (300, 0030, "GR", "GRC", "Grécia", "República Helênica")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (304, 0299, "GL", "GRL", "Groelândia", "Groelândia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (308, 1473, "GD", "GRD", "Granada", "Granada")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (312, 0590, "GP", "GLP", "Guadalupe", "Guadalupe")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (316, 1671, "GU", "GUM", "Guão", "Território do Guão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (320, 0502, "GT", "GTM", "Guatemala", "República da Guatemala")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (324, 0224, "GN", "GIN", "Guiné", "República do Guiné")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (624, 0245, "GW", "GNB", "Guiné-Bissau", "República da Guiné-Bissau")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (328, 0592, "GY", "GUY", "Guiana", "República Cooperativa da Guiana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (332, 0509, "HT", "HTI", "Haiti", "República do Haiti")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (334, 0672, "HM", "HMD", "Ilhas Heard e McDonald", "Território das Ilhas Heard e McDonald")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (336, 0039, "VA", "VAT", "Vaticano", "Estado da Cidade do Vaticano")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (340, 0504, "HN", "HND", "Honduras", "República de Honduras")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (344, 0852, "HK", "HKG", "Hong Kong", "Região Administrativa Especial de Hong Kong da República Popular da China")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (348, 0036, "HU", "HUN", "Hungria", "Hungria")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (352, 0354, "IS", "ISL", "Islândia", "Islândia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (356, 0091, "IN", "IND", "Índia", "República da Índia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (360, 0062, "ID", "IDN", "Indonésia", "República da Indonésia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (364, 0098, "IR", "IRN", "Iran", "República Islâmica do Iran")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (368, 0964, "IQ", "IRQ", "Iraque", "República do Iraque")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (372, 0353, "IE", "IRL", "Irlanda", "Irlanda")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (376, 0972, "IL", "ISR", "Israel", "Estado de Israel")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (380, 0039, "IT", "ITA", "Italia", "República Italiana")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (388, 1876, "JM", "JAM", "Jamaica", "Jamaica")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (392, 0081, "JP", "JPN", "Japão", "Japão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (400, 0962, "JO", "JOR", "Jornânia", "Reino Hachemita da Jordânia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (398, 0007, "KZ", "KAZ", "Cazaquistão", "República do Cazaquistão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (404, 0254, "KE", "KEN", "Quênia", "República do Quênia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (296, 0686, "KI", "KIR", "Kiribati", "República do Kiribati")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (408, 0850, "KP", "PRK", "Coreia do Norte", "República Democrática Popular da Coreia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (410, 0082, "KR", "KOR", "Coreia do Sul", "República da Coreia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (414, 0965, "KW", "KWT", "Kuwait", "Estado do Kuwait")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (417, 0996, "KG", "KGZ", "Quirguistão", "República Quirguiz")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (418, 0856, "LA", "LAO", "Laos", "República Democrática Popular Lau")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (428, 0371, "LV", "LVA", "Letônia", "República da Letônia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (422, 0961, "LB", "LBN", "Líbano", "República Libanesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (426, 0266, "LS", "LSO", "Lesoto", "Reino do Lesoto")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (430, 0231, "LR", "LBR", "Libéria", "República da Libéria")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (434, 0218, "LY", "LBY", "Líbia", "Líbia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (438, 0423, "LI", "LIE", "Liechtenstein", "Principado de Liechtenstein")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (440, 0370, "LT", "LTU", "Lituânia", "República da Lituânia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (442, 0352, "LU", "LUX", "Luxemburgo", "Grão-Ducado do Luxemburgo")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (446, 0853, "MO", "MAC", "Macao", "Macao")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (807, 0389, "MK", "MKD", "Macedônia", "República da Macedônia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (450, 0261, "MG", "MDG", "Madagascar", "República de Madagascar")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (454, 0265, "MW", "MWI", "Malawi", "República de Malawi")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (458, 0060, "MY", "MYS", "Malásia", "Malásia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (462, 0960, "MV", "MDV", "Maldivas", "Reública de Maldivas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (466, 0223, "ML", "MLI", "Mali", "República do Mali")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (470, 0356, "MT", "MLT", "Malta", "República de Malta")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (584, 0692, "MH", "MHL", "Ilhas Marshall", "República das Ilhas Marshall")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (474, 0596, "MQ", "MTQ", "Martinica", "Martinica")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (478, 0222, "MR", "MRT", "Mauritânia", "República Islâmica da Mauritânia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (480, 0230, "MU", "MUS", "Maurício", "República de Maurício")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (175, 0269, "YT", "MYT", "Mayotte", "Departamento de Mayotte")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (484, 0052, "MX", "MEX", "México", "Estados Unidos Mexicanos")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (583, 0691, "FM", "FSM", "Micronésia", "Estados Federados da Micronesia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (498, 0373, "MD", "MDA", "Moldova", "República de Moldova")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (492, 0377, "MC", "MCO", "Mônaco", "Principado de Mônaco")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (496, 0976, "MN", "MNG", "Mongólia", "Mongólia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (500, 1664, "MS", "MSR", "Montserrat", "Montserrat")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (504, 0212, "MA", "MAR", "Marrocos", "Reino de Marrocos")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (508, 0258, "MZ", "MOZ", "Moçambique", "República de Moçambique")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (104, 0095, "MM", "MMR", "Birmânia", "República da União de Myanmar")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (516, 0264, "NA", "NAM", "Namíbia", "República da Namíbia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (520, 0674, "NR", "NRU", "Nauru", "República de Nauru")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (524, 0977, "NP", "NPL", "Nepal", "República Democrática Federativa do Nepal")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (528, 0031, "NL", "NLD", "Holanda", "Holanda")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (530, 0599, "AN", "ANT", "Antilhas Holandesas", "Antilhas Holandesas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (540, 0687, "NC", "NCL", "Nova Caledônia", "Nova Caledônia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (554, 0064, "NZ", "NZL", "Nova Zelândia", "Nova Zelândia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (558, 0505, "NI", "NIC", "Nicarágua", "República da Nicarágua")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (562, 0227, "NE", "NER", "Niger", "República do Niger")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (566, 0234, "NG", "NGA", "Nigéria", "República Federativa da Nigéria")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (570, 0683, "NU", "NIU", "Niue", "Niue")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (574, 0672, "NF", "NFK", "Ilha Norfolk", "Território da Ilha Norfolk")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (580, 1670, "MP", "MNP", "Ilhas Marianas do Norte", "Comunidade das Ilhas Marianas do Norte")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (578, 0047, "NO", "NOR", "Noruega", "Reino da Noruega")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (512, 0968, "OM", "OMN", "Omã", "Sultanato de Omã")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (586, 0092, "PK", "PAK", "Paquistão", "República Islâmica do Paquistão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (585, 0680, "PW", "PLW", "Palau", "República de Palau")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (275, 0970, "PS", "PSE", "Palestina", "Estado da Palestina")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (591, 0507, "PA", "PAN", "Panamá", "República do Panamá")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (598, 0675, "PG", "PNG", "Papua-Nova Guiné", "Estado Independente da Papua-Nova Guiné")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (600, 0595, "PY", "PRY", "Paraguai", "República do Paraguai")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (604, 0051, "PE", "PER", "Peru", "República do Peru")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (608, 0063, "PH", "PHL", "Filipinas", "República das Filipinas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (612, 0672, "PN", "PCN", "Ilhas Picárnia", "Ilhas Picárnia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (616, 0048, "PL", "POL", "Polônia", "República da Polônia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (620, 0351, "PT", "PRT", "Portugal", "República Portuguesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (630, 1787, "PR", "PRI", "Porto Rico", "Comunidade do Porto Rico")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (634, 0974, "QA", "QAT", "Catar", "Estado do Catar")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (638, 0262, "RE", "REU", "Reunião", "Polônia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (642, 0040, "RO", "ROM", "Romênia", "Romênia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (643, 0070, "RU", "RUS", "Rússia", "Federação Russa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (646, 0250, "RW", "RWA", "Ruanda", "República da Ruanda")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (654, 0290, "SH", "SHN", "Santa Helena", "Saint Helena")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (659, 1869, "KN", "KNA", "São Cristóvão", "São Cristóvão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (662, 1758, "LC", "LCA", "Santa Lúcia", "Santa Lúcia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (666, 0508, "PM", "SPM", "São Pedro e Miquelon", "Coletividade Territorial de São Pedro e Miquelon")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (670, 1784, "VC", "VCT", "São Vicente e Granadinas", "São Vicente e Granadinas")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (882, 0684, "WS", "WSM", "Samoa", "Estado Independente de Samoa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (674, 0378, "SM", "SMR", "São Marino", "República de São Marino")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (678, 0239, "ST", "STP", "Sao Tomé e Príncipe", "República Democrática de Sao Tomé e Príncipe")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (682, 0966, "SA", "SAU", "Arábia Saudita", "Reino da Arábia Saudita")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (686, 0221, "SN", "SEN", "Senegal", "República do Senegal")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (688, 0381, "CS", "SRB", "Sérvia e Montenegro", "União Estatal de Sérvia e Montenegro")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (690, 0248, "SC", "SYC", "Seicheles", "República das Seicheles")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (694, 0232, "SL", "SLE", "República da Serra Leoa", "República da Serra Leoa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (702, 0065, "SG", "SGP", "Singapura", "República da Singapura")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (703, 0421, "SK", "SVK", "Eslováquia", "República Eslovaca")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (705, 0386, "SI", "SVN", "Eslovênia", "República da Eslovênia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (090, 0677, "SB", "SLB", "Ilhas Salomão", "Ilhas Salomão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (706, 0252, "SO", "SOM", "Somália", "República da Somália")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (710, 0027, "ZA", "ZAF", "África do Sul", "República da África do Sul")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (239, 0500, "GS", "SGS", "Ilhas Geórgia do Sul e Sandwich do Sul", "Ilhas Geórgia do Sul e Sandwich do Sul")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (724, 0034, "ES", "ESP", "Espanha", "Reino da Espanha")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (144, 0094, "LK", "LKA", "Sri Lanka", "República Democrática Socialista do Sri Lanka")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (736, 0249, "SD", "SDN", "Sudão", "República do Sudão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (740, 0597, "SR", "SUR", "Suriname", "República do Suriname")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (744, 0047, "SJ", "SJM", "Esvalbarde", "Esvalbarde")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (748, 0268, "SZ", "SWZ", "Suazilândia", "Reino da Suazilândia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (752, 0046, "SE", "SWE", "Suécia", "Reino da Suécia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (756, 0041, "CH", "CHE", "Suiça", "Confederação Suiça")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (760, 0963, "SY", "SYR", "Síria", "República Árabe Síria")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (158, 0886, "TW", "TWN", "Taiwan", "Taiwan")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (762, 0992, "TJ", "TJK", "Tajiquistão", "República do Tajiquistão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (834, 0255, "TZ", "TZA", "Tanzânia", "República Unida da Tanzânia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (764, 0066, "TH", "THA", "Tailândia", "Reino da Tailândia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (626, 0670, "TL", "TLS", "Timor-Leste", "República Democrática de Timor-Leste")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (768, 0228, "TG", "TGO", "Togo", "República Togolesa")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (772, 0690, "TK", "TKL", "Toquelau", "Toquelau")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (776, 0676, "TO", "TON", "Tonga", "Reino de Tonga")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (780, 1868, "TT", "TTO", "Trinidad e Tobago", "República da Trinidad e Tobago")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (788, 0216, "TN", "TUN", "Tunísia", "República da Tunísia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (792, 0090, "TR", "TUR", "Turquia", "República da Turquia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (795, 7370, "TM", "TKM", "Turcomenistão", "Turcomenistão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (796, 1649, "TC", "TCA", "Ilhas Turks e Caicos", "Ilhas Turks e Caicos")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (798, 0688, "TV", "TUV", "Tuvalu", "Tuvalu")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (800, 0256, "UG", "UGA", "Uganda", "República de Uganda")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (804, 0380, "UA", "UKR", "Ucrânia", "Ucrânia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (784, 0971, "AE", "ARE", "Emirados Árabes", "Emirados Árabes Unidos")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (826, 0044, "GB", "GBR", "Reino Unido", "Reino Unido da Grã-Bretanha e Irlanda do Norte")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (840, 0001, "US", "USA", "Estados Unidos", "Estados Unidos da América")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (581, 0001, "UM", "UMI", "Ilhas Menores Distantes dos Estados Unidos", "Ilhas Menores Distantes dos Estados Unidos")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (858, 0598, "UY", "URY", "Uruguai", "República Oriental do Uruguai")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (860, 0998, "UZ", "UZB", "Uzbequistão", "República do Uzbequistão")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (548, 0678, "VU", "VUT", "Vanuatu", "República de Vanuatu")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (862, 0058, "VE", "VEN", "Venezuela", "República Bolivariana da Venezuela")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (704, 0084, "VN", "VNM", "Vietnam", "República Socialista do Vietnam")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (092, 1284, "VG", "VGB", "Ilhas Virgens Inglesas", "Ilhas Virgens")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (850, 1340, "VI", "VIR", "Ilhas Virgens (USA)", "Ilhas Virgens dos Estados Unidos")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (876, 0681, "WF", "WLF", "Wallis e Futuna", "Wallis e Futuna")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (732, 0212, "EH", "ESH", "Saara Ocidental", "Saara Ocidental")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (887, 0967, "YE", "YEM", "Iêmen", "República do Iêmen")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (894, 0260, "ZM", "ZMB", "Zâmbia", "República do Zâmbia")
INSERT INTO PAIS (codigo, fone, iso, iso3, nome, nomeFormal) VALUES (716, 0263, "ZW", "ZWE", "Zimbábue", "República do Zimbábue"}